#!/usr/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four 
# million, find the sum of the even-valued terms.
#
# Answer: 4613732

upperLimit = 4000000

oneBack = 2
twoBack = 1

# Starts at 2 since initial oneBack term is even
finalSum = 2 

while (oneBack + twoBack < upperLimit):
    
    # Determine the next Fibbonacci term
    currentTerm = oneBack + twoBack
    
    # Check for even number and add
    if (currentTerm % 2 == 0):
        finalSum += currentTerm

    # Update Fibbonacci terms
    twoBack = oneBack
    oneBack = currentTerm

print "The final sum is: %s" % finalSum
