#!/usr/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four 
# million, find the sum of the even-valued terms.
#
# Answer: 4613732

upper_limit = 4000000

one_back = 2
two_back = 1

# Starts at 2 since initial oneBack term is even
final_sum = 2

while one_back + two_back < upper_limit:
    
    # Determine the next Fibonacci term
    current_term = one_back + two_back
    
    # Check for even number and add
    if current_term % 2 == 0:
        final_sum += current_term

    # Update Fibonacci terms
    two_back = one_back
    one_back = current_term

print "The final sum is: %s" % final_sum
